### PR TITLE
fix: resolve pip and pip-tools version conflict

### PR DESCRIPTION
**Pull request by Jawayria**
JIRA: https://openedx.atlassian.net/browse/BOM-2521

### CODE REVIEW

**Comment by sarina** [comment]
@Jawayria I'm not sure how to review this PR. It seems like many changes must be coming from a script. What has changed here and what type of review do I need to provide?

**Comment by Jawayria** [comment]
> @Jawayria I'm not sure how to review this PR. It seems like many changes must be coming from a script. What has changed here and what type of review do I need to provide?

This PR covers the following:
Resolved pip and pip-tools version conflict
Upgraded python requirements using 'make upgrade' and yes most of the changes were made by 'make upgrade'
Dropped python 3.5 from travis.yml
Resolved quality failure stating `constant names must be upper_case.`

**Comment by sarina** [comment]
@Jawayria awesome thanks. I think the commit message should include all of those changes you mention. Some of this feels like `chore` and some like `fix`. Regardless if you're doing a single commit let's have the commit message list everything that's changing.

Will you be taking care of bumping the version of this XBlock as well, and installing the updated block in edx-platform?

**Comment by sarina** [comment]
You should bump the version here: https://github.com/edx/xblock-free-text-response/blob/master/setup.py#L8 in a separate commit and also update https://github.com/edx/xblock-free-text-response/blob/master/CHANGELOG.md

**Comment by Jawayria** [comment]
> You should bump the version here: https://github.com/edx/xblock-free-text-response/blob/master/setup.py#L8 in a separate commit and also update https://github.com/edx/xblock-free-text-response/blob/master/CHANGELOG.md

Yes Sure

**Review by awais786 — APPROVED** [review]

**Pull request merged**
