### PR TITLE
Change heading from H2 to H3

### PR DESCRIPTION
**Pull request by MHaton**
Minor change to switch the heading from h2 to h3

# Overview
Minor amendment as H2 is the wrong heading level for this component - Problem component headings are H3 so it's inconsistent, and as unit headings are H2 these should come down to H3 for accessibility reasons.

# Test Instructions
- Checkout the branch
- Update settings?
- Anything else?

# TODO
- [ ] Compile static assets
- [ ] Lint all files
- [ ] Pass all tests
- [ ] Bump the version number in `setup.py`
- [ ] Attach screenshots?
- [ ] Code Reviewer 1:
- [ ] Code Reviewer 2:
- [ ] Submit PR against `edx-platform` to bump the version
- [ ] Upload to PyPi

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @MHaton! I've created [OSPR-4896](https://openedx.atlassian.net/browse/OSPR-4896) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.

:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@MHaton Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by MHaton** [comment]
@natabene Sorry for missing your message! I've finally sent the contributor agreement across now.

**Comment by natabene** [comment]
@MHaton Great, thank you. Our Legal team will process it as soon as possible and will let you and me know once you are all set. Please stay tuned for updates.

**Comment by natabene** [comment]
@MHaton Thank you for joining the Open edX community! We have added your user to our records and can now review your code going forward.

**Comment by sarina** [comment]
Seems consistent with other XBlocks such as https://github.com/edx/staff_graded-xblock/blob/master/staff_graded/static/html/staff_graded.html#L2 but I'm checking with someone else

**Comment by edx-webhook** [comment]
@MHaton 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xblock-free-text-response&entry.867055334=https://github.com/edx/xblock-free-text-response/pull/7&entry.1484655318=https://github.com/MHaton&entry.752974735=2020-08-13+16:39&entry.1917517419=2021-03-30+17:28&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
